#!/usr/bin/env bash

check-result() {
    if [ $? -eq 0 ]; then
        echo PASSED $1
    else
        echo FAILED $1
        [ -z "$total_fails" ] && total_fails=0
        ((total_fails++))
    fi
}

this_scripts_dir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)"
cd $this_scripts_dir

emacs -Q \
      -l ../topspace.el \
      -l ./director.el \
      -l ./director-bootstrap.el \
      -l ./tests.el
check-result 'in GUI emacs'

emacs -Q -nw \
      -l ../topspace.el \
      -l ./director.el \
      -l ./director-bootstrap.el \
      -l ./tests.el
check-result 'in terminal emacs'

[ -n "$total_fails" ] && echo FAILED $total_fails tests && exit 1
echo PASSED all tests
